### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Barbz2** [marquisvictor/Modified-GetOldTweets3#13]
HTTP Error 404: Not Found
Try to open in browser: https://twitter.com/search?q=%20from%3Amo4president&src=typd

The code was running perfectly until a few days ago when I started getting this error when searching. This error is given no matter what command I use. This example is with the example commnand (python GetOldTweets3.py --username "mo4president"  --maxtweets 50 --output dataset.csv)

**Comment by kenmbelenzi** [comment]
Hi @Barbz2 were you able to solve the error?..if yes how

**Comment by Barbz2** [comment]
Hi,

No, I wasn't and the software stopped working altogether for me.


Rockstar Developer <notifications@github.com> escreveu no dia quinta,
1/10/2020 à(s) 16:15:

**Comment by marquisvictor** [comment]
Hi, 
I apologize for my absence, I've been quite busy lately. 
Have you tried deleting the whole project folder, and cloning the repository all over. Start from scratch.

**Comment by marquisvictor** [comment]
Please try that and do let me know how that goes here.

**Comment by Barbz2** [comment]
Hi,

I have tried to do that but it's still not working. It might a problem with
how the code is trying to communicate with Twitter, that's what thinking it
might be since it can't find the tweets.

Best wishes,
Bárbara Oliveira.

**Comment by marquisvictor** [comment]
Hi Bárbara, 

Thanks for reaching out, I have recently made some updates to the code README. Please have a look at it. 

regards,
Victor.

**Comment by ashutosh925** [comment]
did you find right solution for this... 
I tried cloning this and followed steps written, I'm still getting same error.

**Comment by marquisvictor** [comment]
What errors?

**Comment by MaxChinni** [comment]
Thank you for your work.

I think we're talking about the OP problem.
Here's my output:
```
max@ez: ~/projects/Optimized-Modified-GetOldTweets3-OMGOT/GetOldTweets3-0.0.10$ python3 GetOldTweets3.py --username "mo4president" --toptweets --maxtweets 100
Downloading tweets...
An error occured during an HTTP request: HTTP Error 404: Not Found
Try to open in browser: https://twitter.com/search?q=%20from%3Amo4president&src=typd

Done. Output file generated "output_got.csv".
```

**Comment by MaxChinni** [comment]
Maybe it's a User Agent problem:
```
max@ez: ~/projects/Optimized-Modified-GetOldTweets3-OMGOT/GetOldTweets3-0.0.10$ curl -v 'https://twitter.com/search?q=%20from%3Amo4president&src=typd' 2>&1 | grep '^. HTTP'
< HTTP/2 400 
max@ez: ~/projects/Optimized-Modified-GetOldTweets3-OMGOT/GetOldTweets3-0.0.10$ curl -v -A "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0" -L -s 'https://twitter.com/search?q=%20from%3Amo4president&src=typd' 2>&1 | grep '^. HTTP'
< HTTP/2 200 
```

**Comment by Olaniyiajayi2** [comment]
The error might be because twitter recently made changes to their API

**Comment by enriquefdez5** [comment]
Hi,
I'm having the same issue and as far as I have read the not modified GetOldTweets3 project is also getting this error.
As @Olaniyiajayi2 pointed it might be because Twitter API changes.
Will you @marquisvictor work on this project to fix the issue? 
I appreciate your answers

Edited because I had not read the entire README, sorry.

**Comment by marquisvictor** [comment]
Hi @enriquefdez5, have you read the README?

**Comment by enriquefdez5** [comment]
Yep, I will have a look at Twint. Thank you!

**Comment by marquisvictor** [comment]
Hello everybody! 

Glad to finally announce that the tool has been fixed. Follow the instructions in the readme carefully to start downloading (old) tweets.
