### ISSUE TITLE
Awesome Code!! But it does not work since yesterday...

### ISSUE THREAD

**Issue by charismayoun** [marquisvictor/Modified-GetOldTweets3#3]
Hi. I think your code is awesome and fast.

But since yesterday it does not work.

I think that's because twitter might change their HTML structure.

Could you check your code is working now?

Thanks a lot.
Regards.

**Comment by marquisvictor** [comment]
Hi @charismayoun have you tried checking your internet connection? That could be an issue. I just tried it now. And it worked.

**Comment by charismayoun** [comment]
Of course I did, but I realized that it sometimes doesn't work.
It cannot receive the json by "jsonResponse = response.read()"

And, it works several days later.

Have you experienced that ever?

**Comment by charismayoun** [comment]
Regarding to search, it is because of CORS.
So, sometimes that code works and sometimes it doesn't.

Do you know how to fix this problem?
