### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hariskr** [marquisvictor/Modified-GetOldTweets3#35]
Is there a way to install this module via pip?

If not, is there a way to use this package in a web-based setting such as Google collab? I would like to introduce my students to this package in class, and not everyone has Python. Many thanks and hopefully this will make your package more popular :)

Note - I tried the following and for the following error

!pip install git+https://github.com/marquisvictor/Optimized-Modified-GetOldTweets3-OMGOT.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/marquisvictor/Optimized-Modified-GetOldTweets3-OMGOT.git
  Cloning https://github.com/marquisvictor/Optimized-Modified-GetOldTweets3-OMGOT.git to /tmp/pip-req-build-v2nvrgb6
  Running command git clone --filter=blob:none --quiet https://github.com/marquisvictor/Optimized-Modified-GetOldTweets3-OMGOT.git /tmp/pip-req-build-v2nvrgb6
  Resolved https://github.com/marquisvictor/Optimized-Modified-GetOldTweets3-OMGOT.git to commit eea77e2b4d9f9b130e2186e37661fe228c8c368b
ERROR: git+https://github.com/marquisvictor/Optimized-Modified-GetOldTweets3-OMGOT.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by marquisvictor** [comment]
Oops, it seems to me that you might need to clone the repository to your Colab environment and access it using Jupyter Notebook's shell command functionality with the "!" symbol.
