### ISSUE TITLE
GetOldTweets3.token.RefreshTokenException: Could not find the Guest token in HTML

### ISSUE THREAD

**Issue by yujinkimmn** [marquisvictor/Modified-GetOldTweets3#37]
Hi, I just found this source code and tried today. Thanks for good tools.

But when I try `python cli.py -s governance` example you mentioned in README.md,
it says 
`GetOldTweets3.token.RefreshTokenException: Could not find the Guest token in HTML`

How can I fix this?

**Comment by C9H13NO3-dev** [comment]
Replace the token.py file in GetOldTweets3 folder with this one.
https://gist.github.com/moxak/ed83dd4169112a0b1669500fe855101a
It's a fix for the twint library, but works here anyways.

**Comment by marquisvictor** [comment]
Thanks for sharing @C9H13NO3-dev

**Comment by marquisvictor** [comment]
FIXED
