### ISSUE TITLE
Whats the max amount of tweets this tool can get?

### ISSUE THREAD

**Issue by BetaHuhn** [marquisvictor/Modified-GetOldTweets3#4]
Nice tool!
It works as expected but when i tried it with a twitter account which has over 20 thousend tweets, the tool came back with only 7848 tweets. Whats the reason for this? Is there a maximum of tweets it can get?
Greetings,
Maxi

**Comment by marquisvictor** [comment]
It queries the twitter search engine till it can no longer get any more information.

**Comment by marquisvictor** [comment]
And thanks for the words.

**Comment by BetaHuhn** [comment]
Any idea why Twitter only returned 7484 of the 20000 Tweets?
