### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by Ledgrev** [marquisvictor/Modified-GetOldTweets3#7]
Hello,

I was trying to extract all tweets containing a certain term with the following command:

`python GetOldTweets3.py --querysearch "tddlkanon" --since 2007-01-01 --until 2017-12-31`

The problem is that I only get empty output. Could someone help me?

**Comment by marquisvictor** [comment]
Hi, 

Try modifying your querysearch parameter. It works for other search keywords.

**Comment by marquisvictor** [comment]
It works with "kanon"

**Comment by Ledgrev** [comment]
Hello, 

Thank you for your quick reply! 

Kind regards!
